<a href="https://colab.research.google.com/github/binarymath/tensorflow2-certification-preparation/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals and concepts of TensorFlow2.0

More especifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way  to speed up your regular Python function)
* Using GPUs with TensorFlow (or TPUs)
* Exercíser to try yourself!

# Introduction to Tensors

In [2]:
# Import TenserFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stand for number of dimensionsvect)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Cjeck the dimension of our vector
vector.ndim

1

# Area of focus, dimensions
## Line x Column

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10, 7],
                              [1, 2],
                              [8, 9],
                              [7, 6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 1.,  2.],
       [ 8.,  9.],
       [ 7.,  6.]], dtype=float16)>

In [ ]:
# What's the number dimnensions of another matrix_matrix
another_matrix.ndim

2

# Dimensions greater than 2.

In [ ]:
# Let's a creater  a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6,]],
                      [[7, 8, 9,],
                       [10, 11, 12]],
                      [[13, 14, 15,],
                       [16, 17, 18,]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


# Create tensors with tf.Variable

In [4]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [6]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor =  tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# How about try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
# Let's try change our unchangeble tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored